theme: jekyll-theme-hacker
description: |
Just a stand-in website to post my ctf writeups and journey into binary exploitation/pwn/exploit development. Temporary layout for now, if you know some webdev help me build this site please, I've got some ideas in mind hit me up on discord, here's my tag: ARIES666#5107.
